In [1]:
import numpy as np
import torch
from torch import nn


class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.conv1 = torch.nn.Conv2d(in_channels=3, out_channels=2, kernel_size=3)
        self.relu1 = torch.nn.ReLU()
        linear_input_size = np.power((224 - 3 + 2 * 0) / 1 + 1, 2) * 2
        self.linear = torch.nn.Linear(int(linear_input_size), 1000)
        self.relu2 = torch.nn.ReLU()  # can't get named ReLU output otherwise

    def forward(self, x):
        x = self.conv1(x)
        x = self.relu1(x)
        x = x.view(x.size(0), -1)
        x = self.linear(x)
        x = self.relu2(x)
        return x
    
import functools
from model_tools.activations.pytorch import load_preprocess_images

preprocessing = functools.partial(load_preprocess_images, image_size=224)

from model_tools.activations.pytorch import PytorchWrapper

activations_model = PytorchWrapper(identifier='my-model', model=MyModel(), preprocessing=preprocessing)

from brainscore import score_model
from model_tools.brain_transformation import ModelCommitment

model = ModelCommitment(identifier='my-model', activations_model=activations_model,
                        # specify layers to consider
                        layers=['conv1', 'relu1', 'relu2'])
# The score_model will score the model on the specified benchmark.
# When the model is asked to output activations for the IT region, it will first search for the best layer
# and then only output this layer's activations.
score = score_model(model_identifier=model.identifier, model=model,
                    benchmark_identifier='dicarlo.MajajHong2015public.IT-pls')
print(score)

C:\Users\LEGION\AppData\Roaming\Python\Python37\site-packages\brainscore\metrics\__init__.py:37: FutureWarning: xarray subclass Score should explicitly define __slots__
  class Score(DataAssembly):


Loading catalog from entrypoints
Loading lookup from C:\Users\LEGION\AppData\Roaming\Python\Python37\site-packages\brainscore\lookup.csv


layers:   0%|          | 0/3 [00:00<?, ?it/s]

activations:   0%|          | 0/3200 [00:00<?, ?it/s]

activations:   0%|          | 0/1024 [00:00<?, ?it/s]

layer packaging:   0%|          | 0/3 [00:00<?, ?it/s]




layer principal components: 100%|██████████| 3/3 [00:46<00:00, 15.42s/it]


layer packaging:   0%|          | 0/3 [00:00<?, ?it/s]

layers: 100%|██████████| 3/3 [04:04<00:00, 81.56s/it]


activations:   0%|          | 0/3200 [00:00<?, ?it/s]

layer packaging:   0%|          | 0/1 [00:00<?, ?it/s]

cross-validation: 100%|██████████| 10/10 [24:23<00:00, 146.38s/it]

<xarray.Score (aggregation: 2)>
array([0.0743526 , 0.00478914])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.22244951...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.81579938...
    model_identifier:      my-model
    benchmark_identifier:  dicarlo.MajajHong2015public.IT-pls


In [10]:
import brainscore
from brainscore.benchmarks import public_benchmark_pool
import torch
import torchvision.models as models

# Define ResNet18
model_ = models.resnet18(pretrained=True)

import functools
from model_tools.activations.pytorch import load_preprocess_images

preprocessing = functools.partial(load_preprocess_images, image_size=224)

from model_tools.activations.pytorch import PytorchWrapper

activations_model = PytorchWrapper(identifier='my-res1', model=model_ , preprocessing=preprocessing)

from brainscore import score_model
from model_tools.brain_transformation import ModelCommitment

model = ModelCommitment(identifier='my-res1', activations_model=activations_model,
                        # specify layers to consider
                        layers=['layer3.0.relu','layer3.1.relu','layer4.0.relu','layer4.1.relu'])

# benchmark = public_benchmark_pool['dicarlo.MajajHong2015public.IT-pls']

# score = benchmark(model)

C:\Users\LEGION\AppData\Roaming\Python\Python37\site-packages\torchvision\models\_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and may be removed in the future, "
C:\Users\LEGION\AppData\Roaming\Python\Python37\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [11]:
score = score_model(model_identifier=model.identifier, model=model,
                    benchmark_identifier='dicarlo.MajajHong2015public.IT-pls')
print(score)

layers:   0%|          | 0/4 [00:00<?, ?it/s]

activations:   0%|          | 0/3200 [00:00<?, ?it/s]

activations:   0%|          | 0/1024 [00:00<?, ?it/s]

layer packaging:   0%|          | 0/4 [00:00<?, ?it/s]






layer principal components: 100%|██████████| 4/4 [00:27<00:00,  6.85s/it]


layer packaging:   0%|          | 0/4 [00:00<?, ?it/s]

layers: 100%|██████████| 4/4 [05:01<00:00, 75.35s/it]


activations:   0%|          | 0/3200 [00:00<?, ?it/s]

layer packaging:   0%|          | 0/1 [00:00<?, ?it/s]

cross-validation: 100%|██████████| 10/10 [09:55<00:00, 59.57s/it]

<xarray.Score (aggregation: 2)>
array([0.54035352, 0.00321373])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.59968387...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.81579938...
    model_identifier:      my-res1
    benchmark_identifier:  dicarlo.MajajHong2015public.IT-pls


In [3]:
import torch
import torchvision.models as models
from resnet18 import *

# Define ResNet18
model_ = torch.load('resnet18_simclr_cifar100_bs4000.pt')

import functools
from model_tools.activations.pytorch import load_preprocess_images

preprocessing = functools.partial(load_preprocess_images, image_size=32)

from model_tools.activations.pytorch import PytorchWrapper

activations_model = PytorchWrapper(identifier='my-res2-cifar', model=model_ , preprocessing=preprocessing)

from brainscore import score_model
from model_tools.brain_transformation import ModelCommitment

model = ModelCommitment(identifier='my-res2-cifar', activations_model=activations_model,
                        # specify layers to consider
                        layers=['layer3.0.relu','layer3.1.relu','layer4.0.relu','layer4.1.relu','avgpool'])

score = score_model(model_identifier=model.identifier, model=model,
                    benchmark_identifier='dicarlo.MajajHong2015public.IT-pls')
print(score)


layers:   0%|          | 0/5 [00:00<?, ?it/s]

activations:   0%|          | 0/3200 [00:00<?, ?it/s]

activations:   0%|          | 0/1024 [00:00<?, ?it/s]

layer packaging:   0%|          | 0/5 [00:00<?, ?it/s]


layer principal components: 100%|██████████| 5/5 [00:00<00:00, 272.64it/s]


layer packaging:   0%|          | 0/5 [00:00<?, ?it/s]

layers: 100%|██████████| 5/5 [01:29<00:00, 17.91s/it]


activations:   0%|          | 0/3200 [00:00<?, ?it/s]

layer packaging:   0%|          | 0/1 [00:00<?, ?it/s]

cross-validation: 100%|██████████| 10/10 [00:16<00:00,  1.64s/it]

<xarray.Score (aggregation: 2)>
array([0.16890929, 0.00338711])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.33528193...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.81579938...
    model_identifier:      my-res2-cifar
    benchmark_identifier:  dicarlo.MajajHong2015public.IT-pls


In [5]:
import torch
import torchvision.models as models
from resnet18 import *

# Define ResNet18
model_ = torch.load('resnet18_simclr_cifar100_parameters11176512_seed0.pt')

import functools
from model_tools.activations.pytorch import load_preprocess_images

preprocessing = functools.partial(load_preprocess_images, image_size=32)

from model_tools.activations.pytorch import PytorchWrapper

activations_model = PytorchWrapper(identifier='ycifar', model=model_ , preprocessing=preprocessing)

from brainscore import score_model
from model_tools.brain_transformation import ModelCommitment

model = ModelCommitment(identifier='ycifar', activations_model=activations_model,
                        # specify layers to consider
                        # layers=['avgpool', 'layer3','layer4'])
                        layers=['layer3.0.relu','layer3.1.relu','layer4.0.relu','layer4.1.relu'])

score = score_model(model_identifier=model.identifier, model=model,
                    benchmark_identifier='dicarlo.MajajHong2015public.IT-pls')
print(score)


layers:   0%|          | 0/4 [00:00<?, ?it/s]

activations:   0%|          | 0/3200 [00:00<?, ?it/s]

activations:   0%|          | 0/1024 [00:00<?, ?it/s]

layer packaging:   0%|          | 0/4 [00:00<?, ?it/s]



layer principal components: 100%|██████████| 4/4 [00:02<00:00,  1.34it/s]


layer packaging:   0%|          | 0/4 [00:00<?, ?it/s]

layers: 100%|██████████| 4/4 [02:38<00:00, 39.73s/it]


activations:   0%|          | 0/3200 [00:00<?, ?it/s]

layer packaging:   0%|          | 0/1 [00:00<?, ?it/s]

cross-validation: 100%|██████████| 10/10 [00:41<00:00,  4.11s/it]

<xarray.Score (aggregation: 2)>
array([0.17416344, 0.00467622])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.34045668...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.81579938...
    model_identifier:      ycifar
    benchmark_identifier:  dicarlo.MajajHong2015public.IT-pls


In [8]:
import torch
import torchvision.models as models
from resnet18 import *
import time
a = True
while a:
    try:
        # Define ResNet18
        model_ = torch.load('resnet18_simclr_cifar100_parameters11176512_seed0_bs512.pt')

        import functools
        from model_tools.activations.pytorch import load_preprocess_images

        preprocessing = functools.partial(load_preprocess_images, image_size=32)

        from model_tools.activations.pytorch import PytorchWrapper

        activations_model = PytorchWrapper(identifier='bs512-cifar', model=model_ , preprocessing=preprocessing)

        from brainscore import score_model
        from model_tools.brain_transformation import ModelCommitment

        model = ModelCommitment(identifier='bs512-cifar', activations_model=activations_model,
                                # specify layers to consider
                                # layers=['avgpool', 'layer3','layer4'])
                                layers=['layer3.0.relu','layer3.1.relu','layer4.0.relu','layer4.1.relu','avgpool'])

        score = score_model(model_identifier=model.identifier, model=model,
                            benchmark_identifier='dicarlo.MajajHong2015public.IT-pls')
        print(score)
        a = False
    except: 
        a = True
        print('wait 30s')
        time.sleep(30)
        

wait 30s
wait 30s
wait 30s
wait 30s
wait 30s
wait 30s
wait 30s
wait 30s
wait 30s
wait 30s
wait 30s
wait 30s
wait 30s
wait 30s


layers:   0%|          | 0/5 [00:00<?, ?it/s]

activations:   0%|          | 0/3200 [00:00<?, ?it/s]

activations:   0%|          | 0/1024 [00:00<?, ?it/s]

layer packaging:   0%|          | 0/5 [00:00<?, ?it/s]




layer principal components: 100%|██████████| 5/5 [00:02<00:00,  2.12it/s]


layer packaging:   0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\LEGION\AppData\Roaming\Python\Python37\site-packages\sklearn\cross_decomposition\_pls.py:97: ConvergenceWarning: Maximum number of iterations reached
  ConvergenceWarning)
layers: 100%|██████████| 5/5 [02:14<00:00, 26.97s/it]


activations:   0%|          | 0/3200 [00:00<?, ?it/s]

layer packaging:   0%|          | 0/1 [00:00<?, ?it/s]

cross-validation: 100%|██████████| 10/10 [00:27<00:00,  2.77s/it]

<xarray.Score (aggregation: 2)>
array([0.18121286, 0.00402782])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.34727848...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.81579938...
    model_identifier:      bs512-cifar
    benchmark_identifier:  dicarlo.MajajHong2015public.IT-pls


In [12]:
import torch
import torch.nn as nn
import torch.nn.functional as F
# import torchvision.transforms as transforms
from torch.utils.data import DataLoader, Dataset
# from torchvision.datasets import CIFAR100
import numpy as np
from resnet18 import ResNet18_NoFC, ProjectionHead

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cpu


In [52]:
import torch
import torchvision.models as models

# Define ResNet18
model_ = models.resnet18(pretrained=True).to('cuda')
# print(model_)

import functools
from model_tools.activations.pytorch import load_preprocess_images

preprocessing = functools.partial(load_preprocess_images, image_size=224)

from model_tools.activations.pytorch import PytorchWrapper

activations_model = PytorchWrapper(identifier='my-model7', model=model_ , preprocessing=preprocessing)

from brainscore import score_model
from model_tools.brain_transformation import ModelCommitment

model = ModelCommitment(identifier='my-model7', activations_model=activations_model,
                        # specify layers to consider
                        layers=['layer4'])
# The score_model will score the model on the specified benchmark.
# When the model is asked to output activations for the IT region, it will first search for the best layer
# and then only output this layer's activations.
score = score_model(model_identifier=model.identifier, model=model,
                    benchmark_identifier='dicarlo.MajajHong2015public.IT-pls')
print(score)

# from brainscore.benchmarks import public_benchmark_pool

# benchmark = public_benchmark_pool['dicarlo.MajajHong2015public.IT-pls']

# score = benchmark(resnet18)

layers:   0%|          | 0/1 [00:00<?, ?it/s]

activations:   0%|          | 0/3200 [00:00<?, ?it/s]

activations:   0%|          | 0/1024 [00:00<?, ?it/s]

layer packaging:   0%|          | 0/1 [00:00<?, ?it/s]




layer principal components:   0%|          | 0/1 [00:00<?, ?it/s]


layer principal components: 100%|██████████| 1/1 [00:01<00:00,  1.43s/it]


layer packaging:   0%|          | 0/1 [00:00<?, ?it/s]


layers: 100%|██████████| 1/1 [00:49<00:00, 49.25s/it]


activations:   0%|          | 0/3200 [00:00<?, ?it/s]

layer packaging:   0%|          | 0/1 [00:00<?, ?it/s]

cross-validation: 100%|██████████| 10/10 [08:51<00:00, 53.19s/it]

<xarray.Score (aggregation: 2)>
array([0.47523326, 0.00368762])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.56238896...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.81579938...
    model_identifier:      my-model7
    benchmark_identifier:  dicarlo.MajajHong2015public.IT-pls


In [46]:
print(score.raw, score.ceiling)
(0.47523326)/(0.81579938)

<xarray.Score (aggregation: 2)>
array([0.56238896, 0.00368762])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:      <xarray.Score (split: 10, neuroid: 168)>\narray([[0.324818  , 0... <xarray.Score (aggregation: 2)>
array([0.81579938, 0.00144955])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:      <xarray.DataArray (split: 10, neuroid: 168)>\narray([[0.1951266...


0.5825369222516448

In [ ]:
<xarray.Score (aggregation: 2)>
array([0.47523326, 0.00368762])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.56238896...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.81579938...
    model_identifier:      my-model3
    benchmark_identifier:  dicarlo.MajajHong2015public.IT-pls

In [1]:
# from candidate_models.model_commitments import brain_translated_pool

# identifier = 'alexnet'
# model = brain_translated_pool[identifier]
import torch
import torchvision.models as models

# Define ResNet18
model_ = models.alexnet(pretrained=True)
print(model_)


AlexNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
  (classifier): Sequential(
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(in_features=9216, out_features=4096, bias=True)
 

In [2]:
import functools
from model_tools.activations.pytorch import load_preprocess_images
print('b')
preprocessing = functools.partial(load_preprocess_images, image_size=224)

from model_tools.activations.pytorch import PytorchWrapper
print('a')
activations_model = PytorchWrapper(identifier='my-alxenet', model=model_ , preprocessing=preprocessing)

from brainscore import score_model
from model_tools.brain_transformation import ModelCommitment
print('c')
model = ModelCommitment(identifier='my-alxenet', activations_model=activations_model, layers=['features.11'])
# The score_model will score the model on the specified benchmark.
# When the model is asked to output activations for the IT region, it will first search for the best layer
# and then only output this layer's activations.
score = score_model(model_identifier=model.identifier, model=model, benchmark_identifier='dicarlo.MajajHong2015public.IT-pls')

b
a


c:\Users\LEGION\miniconda3\envs\scaling_law\lib\site-packages\brainscore\metrics\__init__.py:37: FutureWarning: xarray subclass Score should explicitly define __slots__
  class Score(DataAssembly):


c
Loading catalog from entrypoints
Loading lookup from c:\Users\LEGION\miniconda3\envs\scaling_law\lib\site-packages\brainscore\lookup.csv


layers:   0%|          | 0/1 [00:00<?, ?it/s]

activations:   0%|          | 0/3200 [00:00<?, ?it/s]

c:\Users\LEGION\miniconda3\envs\scaling_law\lib\site-packages\boto3\compat.py:82: PythonDeprecationWarning: Boto3 will no longer support Python 3.7 starting December 13, 2023. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.8 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)


In [1]:
import h5py

ImportError: DLL load failed: 找不到指定的程序。

In [70]:
score

<xarray.Score (aggregation: 2)>
array([0.50479693, 0.00269367])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.57961781...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.81579938...
    model_identifier:      my-alxenet2
    benchmark_identifier:  dicarlo.MajajHong2015public.IT-pls

In [68]:
score

<xarray.Score (aggregation: 2)>
array([0.40076219, 0.00312042])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.51644817...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.81579938...
    model_identifier:      my-alxenet
    benchmark_identifier:  dicarlo.MajajHong2015public.IT-pls

In [12]:
import numpy as np
from typing import List, Tuple
from brainscore.benchmarks.screen import place_on_screen

from brainscore.model_interface import BrainModel
from brainio.assemblies import DataAssembly

class RandomITModel(BrainModel):
    def __init__(self):
        self._num_neurons = 500
        # to note which time we are recording
        self._time_bin_start = None
        self._time_bin_end = None
    
    def look_at(self, stimuli, **kwargs):
        print(f"Looking at {len(stimuli)} stimuli")
        rnd = np.random.RandomState(0)
        recordings = DataAssembly(rnd.rand(len(stimuli), self._num_neurons, 1),
                              coords={'stimulus_id': ('presentation', stimuli['stimulus_id']),
                                      'object_name': ('presentation', stimuli['object_name']),
                                      'neuroid_id': ('neuroid', np.arange(self._num_neurons)),
                                      'region': ('neuroid', ['IT'] * self._num_neurons),
                                      'time_bin_start': ('time_bin', [self._time_bin_start]),
                                      'time_bin_end': ('time_bin', [self._time_bin_end])},
                              dims=['presentation', 'neuroid', 'time_bin'])
        recordings.name = 'random_it_model'
        return recordings
    
    def start_task(self, task, **kwargs):
        print(f"Starting task {task}")
        if task != BrainModel.Task.passive:
            raise NotImplementedError()

    def start_recording(self, recording_target=BrainModel.RecordingTarget, time_bins=List[Tuple[int]]):
        print(f"Recording from {recording_target} during {time_bins} ms")
        if str(recording_target) != "IT":
            raise NotImplementedError(f"RandomITModel only supports IT, not {recording_target}")
        if len(time_bins) != 1:
            raise NotImplementedError(f"RandomITModel only supports a single start-end time-bin, not {time_bins}")
        time_bins = time_bins[0].tolist()
        self._time_bin_start, self._time_bin_end = time_bins[0], time_bins[1]
    
    def visual_degrees(self):
        print("Declaring model to have a visual field size of 8 degrees")
        return 8

model = RandomITModel()
from brainscore import score_model
score = score_model(model_identifier='mymodel', model=model, benchmark_identifier='dicarlo.MajajHong2015public.IT-pls')
print(score)

<xarray.Score (aggregation: 2)>
array([1.32927606e-05, 4.04256995e-03])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([-0.0029743...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.81579938...
    model_identifier:      mymodel
    benchmark_identifier:  dicarlo.MajajHong2015public.IT-pls


In [11]:
center, error = score.sel(aggregation='center'), score.sel(aggregation='error')
print(f"score: {center.values:.3f}+-{error.values:.3f}")
unceiled_scores = score.raw
print(unceiled_scores)
raw_scores = score.raw.raw
print(raw_scores)

score: 0.000+-0.004
<xarray.Score (aggregation: 2)>
array([-0.00297434,  0.00404257])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:      <xarray.Score (split: 10, neuroid: 168)>\narray([[-0.07013847, ...
<xarray.Score (split: 10, neuroid: 168)>
array([[-0.07013847, -0.13526484, -0.00398237, ...,  0.01279745,
         0.00486601,  0.05982493],
       [-0.02456292,  0.02610781,  0.03680893, ...,  0.05548382,
         0.0882642 ,  0.04073444],
       [-0.03694351, -0.00881172,  0.03439634, ..., -0.00529333,
         0.03286495,  0.0602468 ],
       ...,
       [-0.02413559, -0.00473873,  0.01249379, ..., -0.04916033,
         0.02889037, -0.04196739],
       [ 0.0049915 , -0.03839387, -0.00863761, ...,  0.09563656,
         0.10167743,  0.04610749],
       [-0.02287174, -0.02757991,  0.04398252, ...,  0.04969161,
         0.0334736 , -0.04560006]])
Coordinates:
  * split       (split) int64 0 1 2 3 4 5 6 7 8 9
  * neuroid     (neuroid) MultiIndex
  

In [15]:
from model_tools.activations.pytorch import PytorchWrapper
from model_tools.activations.pytorch import load_preprocess_images

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, Dataset
from torchvision.datasets import CIFAR100
import numpy as np
from networks import *

# class BasicBlock(nn.Module):
#     expansion = 1

#     def __init__(self, in_channels, out_channels, stride=1):
#         super(BasicBlock, self).__init__()
#         self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=stride, padding=1, bias=False)
#         self.bn1 = nn.BatchNorm2d(out_channels)
#         self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=1, padding=1, bias=False)
#         self.bn2 = nn.BatchNorm2d(out_channels)

#         self.shortcut = nn.Sequential()
#         if stride != 1 or in_channels != self.expansion * out_channels:
#             self.shortcut = nn.Sequential(
#                 nn.Conv2d(in_channels, self.expansion * out_channels, kernel_size=1, stride=stride, bias=False),
#                 nn.BatchNorm2d(self.expansion * out_channels)
#             )

#     def forward(self, x):
#         out = F.relu(self.bn1(self.conv1(x)))
#         out = self.bn2(self.conv2(out))
#         out += self.shortcut(x)
#         out = F.relu(out)
#         return out

# class ResNet(nn.Module):
#     def __init__(self, block, num_blocks, num_classes=100):
#         super(ResNet, self).__init__()
#         self.in_channels = 64

#         self.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
#         self.bn1 = nn.BatchNorm2d(64)
#         self.layer1 = self._make_layer(block, 64, num_blocks[0], stride=1)
#         self.layer2 = self._make_layer(block, 128, num_blocks[1], stride=2)
#         self.layer3 = self._make_layer(block, 256, num_blocks[2], stride=2)
#         self.layer4 = self._make_layer(block, 512, num_blocks[3], stride=2)
#         # Removed the final fully connected layer self.linear = nn.Linear(512 * block.expansion, num_classes)

#     def _make_layer(self, block, out_channels, num_blocks, stride):
#         strides = [stride] + [1] * (num_blocks - 1)
#         layers = []
#         for stride in strides:
#             layers.append(block(self.in_channels, out_channels, stride))
#             self.in_channels = out_channels * block.expansion
#         return nn.Sequential(*layers)

#     def forward(self, x):
#         out = F.relu(self.bn1(self.conv1(x)))
#         out = self.layer1(out)
#         out = self.layer2(out)
#         out = self.layer3(out)
#         out = self.layer4(out)
#         out = F.avg_pool2d(out, 4)
#         out = out.view(out.size(0), -1)
#         # Removed the final fully connected layer out = self.linear(out)
#         return out

# def ResNet18():
#     return ResNet(BasicBlock, [2, 2, 2, 2])
# Define ResNet18
model_ = torch.load('resnet18_simclr_cifar100_bigbz.pt').to('cuda')
print(model_)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (shortcut): Sequential()
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, Dataset
from torchvision.datasets import CIFAR100
import numpy as np
from networks import *

model_ = torch.load('resnet18_simclr_cifar100_bigbz.pt').to('cuda')
print(model_)

In [1]:
import functools
from model_tools.activations.pytorch import load_preprocess_images
from brainscore import score_model
from model_tools.brain_transformation import ModelCommitment
from model_tools.activations.pytorch import PytorchWrapper

preprocessing = functools.partial(load_preprocess_images, image_size=32)

/home/mila/p/pingsheng.li/venvs/scaling_law/lib/python3.7/site-packages/brainscore/metrics/__init__.py:37: FutureWarning: xarray subclass Score should explicitly define __slots__
  class Score(DataAssembly):


In [3]:
activations_model = PytorchWrapper(identifier='my-res-cifar100', model=model_ , preprocessing=preprocessing)

In [4]:
model = ModelCommitment(identifier='my-res-cifar100', activations_model=activations_model,
                        # specify layers to consider
                        layers=['layer4'])
# The score_model will score the model on the specified benchmark.
# When the model is asked to output activations for the IT region, it will first search for the best layer
# and then only output this layer's activations.

In [ ]:
score = score_model(model_identifier=model.identifier, model=model,
                    benchmark_identifier='dicarlo.MajajHong2015public.IT-pls')

Loading catalog from entrypoints
Loading lookup from /home/mila/p/pingsheng.li/venvs/scaling_law/lib/python3.7/site-packages/brainscore/lookup.csv


cross-validation:   0%|          | 0/10 [00:00<?, ?it/s]